FROM golang:1.13

RUN apt-get update && \
    apt-get install git libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev -y

RUN go get github.com/onsi/ginkgo/ginkgo

RUN export GOPATH=/tmp/gopath && \
    git clone https://github.com/containers/skopeo $GOPATH/src/github.com/containers/skopeo && \
    cd $GOPATH/src/github.com/containers/skopeo && make binary-local && \
    cp skopeo /usr/bin/skopeo && rm -r $GOPATH

ENV GO111MODULE=on
ENV GOFLAGS=-mod=vendor

WORKDIR /tweed

COPY --from=registry /etc/docker/registry/config.yml /etc/docker/registry/config.yml
COPY --from=registry /bin/registry /bin/registry

RUN nohup bash -c "registry serve /etc/docker/registry/config.yml &" && \
    skopeo --insecure-policy copy --dest-tls-verify=false \
           docker://curlimages/curl docker://localhost:5000/curl:latest

ENTRYPOINT /bin/bash
